# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            SkunkWorks
tagline:          'My experiments with all things web'
description:      'This blog will let me tell u guys what and how each of my project is done. Developed with <a href = "http://jekyllrb.com/" target="_blank">Jekyll</a>, <a href = "http://demo.getpoole.com/" target="_blank">Poole</a> and Powered by <a href="https://github.com" target="_blank">Github</a>. Made with <b>Geekiness</b> & <b>Nerdyness</b> by your fellow geek <a href="http://rajeev-reddy.com" target="_blank">Rajeev Reddy</a>'
url:              http://blog.rajeev-reddy.com/
baseurl:          /

author:
  name:           'Rajeev Reddy'
  url:            http://rajeev-reddy.com/

paginate:         2

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/drreddy/drreddy.github.io
